# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbda32f7116268c2a9488b01ae5a675db18fcece016993c24c57121543e34f16f466a62ef1858cee0c894dd6daaf65e61ed3aebb8b9dac26df6082d633f6c232

test:
  secret_key_base: 8625b993685f87ccecc099de766d02ef0276120de587b2002ddcd076277ba6714f56f3a2e05325348ab8839ed6a4f835e41312cb1f0b0a76fbfb22108cd5fde6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
